###GET
GET http://localhost:4000/api/jobs

###POST
POST http://localhost:4000/api/jobs
Content-Type: application/json

{
  "title": "Job title 1",
  "type": "Job type 1",
  "description": "Job description 1",
  "company": {
    "name": "Company 1",
    "contactEmail": "email1@gmail.com",
    "contactPhone": "012345678"
  },
  "location": "Vantaa",
  "salary": 4000
}

###GET by type
GET http://localhost:4000/api/jobs/type/Full-time

###GET search by location
GET http://localhost:4000/api/jobs/location/Helsinki

###GET filter by salary
GET http://localhost:4000/api/jobs/salary?min=5000&max=6000

###GET count by type
GET http://localhost:4000/api/jobs/count/type/Part-time